### ISSUE TITLE
Collectionview will be jerky when cells count is too much

### ISSUE THREAD

**Issue by RobotAmiee** [SureCase/WaterfallCollectionView#2]
For example when i set numberOfSections to 30 and numberOfItemsInSection to 30, it will be jerky when scroll.

**Comment by RGSSoftware** [comment]
This problem seem to come from {FRGWaterfallCollectionViewLayout.stickyHeader=YES} being set. This ivar is set by default. 

I suggest setting a few other ivar to nil within FRGWaterfallCollectionViewLayout.m - (void)setup method to deal with other problems.

**Comment by phamquy** [comment]
i think it is not complete fix. with this fix you can ignore recalculate layout when use dragging or scrollview is decelerating, but when it's  bouncing, the layout object recalculate the whole cell out again. You see it by scroll the collection view the bottom or top and let it bounce.

**Comment by carsten-wenderdel** [comment]
The bug fix introduced another bug. When the datasource changes while the view is moving we have a problem.
Other code then might call "invalidateLayout", but "prepareLayout" doesn't do anything. In the app I'm working on this has been the number one reason for crashes, so we switched back to an old version of WaterfallCollectionView.
Unfortunately I don't see an easy fix ...
